version: '3'
services:
    call-weather-service:
        build: ./call-weather-service
        command: npm start
        volumes:
         - ./call-weather-service:/usr/app/
         - /usr/app/node_modules
        ports:
         - "4000:4000"
    weather-service:
        build: ./weather-service
        command: npm start
        volumes:
         - ./weather-service:/usr/app/
         - /usr/app/node_modules
        ports:
         - "5000:5000"
    redis:
        image: "redis:alpine"
        ports:
            - "6379:6379"
        volumes:
            - ./redis-docker/config/redis.conf:/redis.conf
        command: [ "redis-server", "/redis.conf" ]